# For i3status-rust version 0.31.9
# Install with `cargo install i3status-rs
#
[icons]
icons = "awesome6"

[theme]
theme = "gruvbox-dark"
[theme.overrides]
idle_fg = "#d79921"
separator = ""

[[block]]
block = "sound"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
warning = 10.0
alert = 5.0

[[block]]
block = "memory"
format = " $icon $mem_used_percents "
warning_mem = 90

[[block]]
block = "nvidia_gpu"
interval = 2
format = " $icon $utilization $temperature "

[[block]]
block = "cpu"
interval = 2
format = " $icon $utilization "
info_cpu = 45.0

[[block]]
block = "temperature"
interval = 2
inputs = ["Tccd1", "Tctl"]
format = " $icon $max "
idle = 55.0
info = 65.0

[[block]]
block = "time"
interval = 2
format = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %H:%M:%S') "
