[icons]
icons = "awesome"

[theme]
theme = "gruvbox-dark"
[theme.overrides]
idle_fg = "#d79921"
separator = ""

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
warning = 10.0
alert = 5.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "$mem_used_percents"
format_swap = "$swap_used_percents"
warning_mem = 90

[[block]]
block = "nvidia_gpu"
interval = 2
format = "$utilization $temperature"

[[block]]
block = "cpu"
interval = 2
format = "$utilization"

[[block]]
block = "temperature"
collapsed = false
format = "$average"
interval = 2

[[block]]
block = "load"
interval = 2
format = "$1m"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 2
format = "%a %Y-%m-%d %H:%M:%S"
